### ISSUE TITLE
Cannot integrate with the ActiveAndroid library

### ISSUE THREAD

**Issue by r0boto** [commonsguy/sqlcipher-for-android-artifact#1]
Hello, 

i installed sqlcipher-for-android-artifact using the gradle build system and i would like to ask how can i integrate it with ActiveAndroid library?

I found the Cache.java class inside of the activeAndroid and method inside of this class.

```
	public static synchronized SQLiteDatabase openDatabase() {
		return sDatabaseHelper.getWritableDatabase();
	}
```

And i tried to password string here, but files are not editable. 
I tried to find something in your example code, but without luck to integrate it together.

How can i use with the ActiveAndroid please?

Many thanks for any advice.

**Comment by commonsguy** [comment]
Please read [the documentation](https://github.com/commonsguy/sqlcipher-for-android-artifact#questions) for getting support with SQLCipher for Android. This is merely an unofficial packaging of SQLCipher for Android as a Maven-style artifact for use with Android Studio and Gradle for Android.
